---
###############################################################################
# Config
###############################################################################

- name: '{{ "Config | filesystem | set " ~ left_4_dead__cfg._motd_file }}'
  ansible.builtin.copy:
    dest: '{{ left_4_dead__cfg._motd_file }}'
    owner: '{{ steam__ctx._user }}'
    group: '{{ steam__ctx._group }}'
    mode: '0644'
    content: '{{ left_4_dead__cfg._motd }}'

- name: '{{ "Config | filesystem | set " ~ left_4_dead__cfg._host_file }}'
  ansible.builtin.copy:
    dest: '{{ left_4_dead__cfg._host_file }}'
    owner: '{{ steam__ctx._user }}'
    group: '{{ steam__ctx._group }}'
    mode: '0644'
    content: '{{ left_4_dead__cfg._host }}'

- name: '{{ "Config | filesystem | set " ~ left_4_dead__cfg._server_file }}'
  ansible.builtin.template:
    src: 'server.cfg.j2'
    dest: '{{ left_4_dead__cfg._server_file }}'
    owner: '{{ steam__ctx._user }}'
    group: '{{ steam__ctx._group }}'
    mode: '0644'
  vars:
    server: '{{ left_4_dead__cfg._server }}'

- name: '{{ "Config | filesystem | set " ~ left_4_dead__cfg._admins_file }}'
  when: left_4_dead_flg_sourcemod
  ansible.builtin.template:
    src: 'admins_simple.ini.j2'
    dest: '{{ left_4_dead__cfg._admins_file }}'
    owner: '{{ steam__ctx._user }}'
    group: '{{ steam__ctx._group }}'
    mode: '0600'
