---
###############################################################################
# Install
###############################################################################
# Install location is relative to base installation directory. This is **NOT**
# customizable, contrary to many mis-documented Internet configurations.
#
# server.cfg must be located in left4dead/cfg and can only be referenced on
# start using the relative path from that location (server.cfg).
#
# Reference:
# * https://github.com/r-pufky/steam/blob/master/docs/examples/left-4-dead.md
# * https://wiki.alliedmods.net/Installing_Metamod:Source
# * https://wiki.alliedmods.net/Installing_SourceMod

- name: 'Install | steamcmd'
  ansible.builtin.import_role:
    name: 'r_pufky.game.steam'
  vars:
    steam_flg_update: false
    steam_flg_container: '{{ left_4_dead_flg_container }}'
    steam_flg_metamod: '{{ left_4_dead_flg_metamod }}'
    steam_flg_sourcemod: '{{ left_4_dead_flg_sourcemod }}'
    steam_srv_token: '{{ left_4_dead__srv._token }}'
    steam_cfg_mod_branch: '{{ left_4_dead__srv._mod_branch }}'
    steam_cfg_mm_build: '{{ left_4_dead__srv._mm_build }}'
    steam_cfg_sm_build: '{{ left_4_dead__srv._sm_build }}'

- name: 'Install | filesystem | find current installation'
  ansible.builtin.stat:
    path: '{{ left_4_dead___app._bin }}'
  register: left_4_dead__installed

- name: 'Install | fact | set install state'
  ansible.builtin.set_fact:
    left_4_dead__cfg: "{{ left_4_dead__cfg | r_pufky.data.v3(

        _is_installed=left_4_dead__installed.stat.exists,
        _admin_ini=(
          left_4_dead___app._root_d ~ steam__ctx._sourcemod_dirs[0] ~
          '/configs/admins_simple.ini'
        ),
      ) }}"

- name: '{{ "Install | filesystem | " ~ left_4_dead___app._root_d }}'
  ansible.builtin.file:
    path: '{{ left_4_dead___app._root_d }}'
    owner: '{{ steam__ctx._uid }}'
    group: '{{ steam__ctx._gid }}'
    mode: '0755'
    state: 'directory'

- name: '{{ "Install | filesystem | " ~ left_4_dead___app._update_server }}'
  ansible.builtin.template:
    src: 'update_server.j2'
    dest: '{{ left_4_dead___app._update_server }}'
    owner: '{{ steam__ctx._user }}'
    group: '{{ steam__ctx._group }}'
    mode: '0755'

- name: 'Install | systemd | set left_4_dead.service'
  ansible.builtin.template:
    src: 'systemd/left_4_dead.service.j2'
    dest: '/etc/systemd/system/left_4_dead.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
