---
- name: 'Converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Converge | apply r_pufky.game.left_4_dead'
      ansible.builtin.include_role:
        name: 'r_pufky.game.left_4_dead'
